services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'jamestelfer/github-app-auth']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
