services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'chinmina/chinmina-git-credentials']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
