name: Github App Auth
description: |
  Adds a Git credential helper that authorizes a pipeline to access its Github
  using HTTPS and a time-limited token.

  The helper agent (separate) is accessed via HTTP, using the Buildkite Agent
  OIDC token as its authorization.
author: https://github.com/jamestelfer
requirements: []
configuration:
  properties:
    vendor-url:
      type: string
      description: The URL of the helper agent that vends a token for a pipeline.
    audience:
      type: string
      description: (Default `github-app-auth:default`.) The audience to use for the Buildkite OIDC JWT that is sent to the vendor agent. Must match the setting in the vendor agent.
  additionalProperties: false
