name: Github App Auth
description: |
  Adds a Git credential helper that authorizes a pipeline to access its Github
  using HTTPS and a time-limited token.

  The helper agent (separate) is accessed via HTTP, using the Buildkite Agent
  OIDC token as its authorization.
author: https://github.com/chinmina
requirements: []
configuration:
  properties:
    chinmina-url:
      type: string
      description: |
        The URL of the Chinmina Bridge agent that creates a token for a pipeline.
        If not provided, falls back to the CHINMINA_DEFAULT_URL environment variable.
        This parameter is required and must be set via either mechanism.
    audience:
      type: string
      description: |
        The audience to use for the Buildkite OIDC JWT that is sent to the vendor
        agent. Must match the setting in the vendor agent.

        Priority: plugin parameter > CHINMINA_DEFAULT_AUDIENCE environment variable > "chinmina:default"
    profiles:
      type: array
      description: |
        An array of profiles to use for the Git credential helper. If unset,
        the default profile and endpoint will be used to obtain tokens for the
        current pipeline.
    exclusive:
      type: boolean
      description: |
        When true, clears existing credential helpers before adding the plugin's
        helpers. This allows you to replace previously configured credential
        helpers (including default Chinmina profiles) with the profiles specified
        in this plugin configuration. Ensure at least one profile has contents:read
        permission, otherwise checkout will fail.
  additionalProperties: false
