#!/bin/bash
set -euo pipefail

original_prefix="BUILDKITE_PLUGIN_GITHUB_APP_AUTH_"
prefix="BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_"


get_parameter() {
  local key="$1"
  local name="${prefix}${key}"
  local value="${!name:-}"

  if [ -z "$value" ]; then
    name="${original_prefix}${key}"
    value="${!name:-}"
  fi
  echo "${value}"
}

chinmina_url="$(get_parameter "CHINMINA_URL")"
vendor_url_compat="$(get_parameter "VENDOR_URL")"
audience="$(get_parameter "AUDIENCE")"
profiles="$(get_parameter "PROFILES")"

echo "Profile: $profiles"

# allow the old name of the parameter to be used
chinmina_url="${chinmina_url:-$vendor_url_compat}"

if [ -z "$chinmina_url" ]; then
  echo "~~~ :error: Missing required parameter chinmina-url"
  exit 1
fi

if [ -z "$audience" ]; then
  audience="chinmina:default"
fi

if [ -z "$profiles" ]; then
  profiles="repo:default"
fi

echo "~~~ :git: :github: Configuring Git to authenticate via Chinmina"

plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"

echo "Credential helper will run from plugin root ${plugin_root}"

# set up the helper using environment variables for git config, as defined at
# https://git-scm.com/docs/git-config#ENVIRONMENT

git_config_add() {
    local key="$1"
    local value="$2"

    local currentCount="${GIT_CONFIG_COUNT:-0}"

    index=$(( currentCount ))

    # index is incremented each time a setting is added
    export GIT_CONFIG_COUNT=$(( index + 1 ))
    export "GIT_CONFIG_KEY_${index}=${key}"
    export "GIT_CONFIG_VALUE_${index}=${value}"
}



git_config_add "credential.https://github.com.usehttppath" "true"

for profile in ${profiles}; do
  if [[ "$profile" != org:* && "$profile" != repo:* ]]; then
    echo "~~~ :error: Invalid profile: $profile. Must start with 'org:' or 'repo:'"
    exit 1
  fi
  git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${chinmina_url} ${audience} ${profile}"
done

