#!/bin/bash
set -euo pipefail

original_prefix="BUILDKITE_PLUGIN_GITHUB_APP_AUTH_"
prefix="BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_"

get_parameter() {
  local key="$1"
  local name="${prefix}${key}"
  local value="${!name:-}"

  if [ -z "$value" ]; then
    name="${original_prefix}${key}"
    value="${!name:-}"
  fi
  echo "${value}"
}

vendor_url="$(get_parameter "VENDOR_URL")"
audience="$(get_parameter "AUDIENCE")"

if [ -z "$vendor_url" ]; then
  echo "~~~ :error: Missing required parameter vendor-url"
  exit 1
fi

if [ -z "$audience" ]; then
  audience="chinmina:default"
fi

echo "~~~ :git: :github: Configuring Git to authenticate via Chinmina"

plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"

echo "Credential helper will run from plugin root ${plugin_root}"

# set up the helper using environment variables for git config, as defined at
# https://git-scm.com/docs/git-config#ENVIRONMENT

git_config_add() {
    local key="$1"
    local value="$2"

    local currentCount="${GIT_CONFIG_COUNT:-0}"

    index=$(( currentCount ))

    # index is incremented each time a setting is added
    export GIT_CONFIG_COUNT=$(( index + 1 ))
    export "GIT_CONFIG_KEY_${index}=${key}"
    export "GIT_CONFIG_VALUE_${index}=${value}"
}

git_config_add "credential.https://github.com.usehttppath" "true"
git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${vendor_url} ${audience}"
