#!/bin/bash
set -euo pipefail

original_prefix="BUILDKITE_PLUGIN_GITHUB_APP_AUTH_"
prefix="BUILDKITE_PLUGIN_CHINMINA_GIT_CREDENTIALS_"

# Reads either a value or a list from plugin config into a global result array
# Returns success if values were read
# Inspired by: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/4ac4d6d/lib/shared.bash#L69-L87
plugin_read_list_into_result() {
  local prefix="$1"
  local parameter="${prefix}_0"
  result=()

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      result+=("${!parameter}")
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    result+=("${!prefix}")
  fi

  [[ ${#result[@]} -gt 0 ]] || return 1
}

get_parameter() {
  local key="$1"
  local name="${prefix}${key}"
  local value="${!name:-}"

  if [ -z "$value" ]; then
    name="${original_prefix}${key}"
    value="${!name:-}"
  fi
  echo "${value}"
}

chinmina_url="$(get_parameter "CHINMINA_URL")"
vendor_url_compat="$(get_parameter "VENDOR_URL")"
audience="$(get_parameter "AUDIENCE")"

# allow the old name of the parameter to be used
chinmina_url="${chinmina_url:-$vendor_url_compat}"

if [ -z "$chinmina_url" ]; then
  echo "~~~ :error: Missing required parameter chinmina-url"
  exit 1
fi

if [ -z "$audience" ]; then
  audience="chinmina:default"
fi

profiles=()
# read profiles from the plugin config, returns an array
if plugin_read_list_into_result "${prefix}PROFILES"; then
  profiles=("${result[@]}")
fi

if [[ ${#profiles[@]} -eq 0 ]]; then
  profiles=("repo:default")
fi

echo "~~~ :git: :github: Configuring Git to authenticate via Chinmina"

plugin_root="$(cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"

echo "Credential helper will run from plugin root ${plugin_root}"

# set up the helper using environment variables for git config, as defined at
# https://git-scm.com/docs/git-config#ENVIRONMENT

git_config_add() {
    local key="$1"
    local value="$2"

    local currentCount="${GIT_CONFIG_COUNT:-0}"

    index=$(( currentCount ))

    # index is incremented each time a setting is added
    export GIT_CONFIG_COUNT=$(( index + 1 ))
    export "GIT_CONFIG_KEY_${index}=${key}"
    export "GIT_CONFIG_VALUE_${index}=${value}"
}

git_config_add "credential.https://github.com.usehttppath" "true"

# iterate over all provided profiles and configure a credential helper for each one
for profile in "${profiles[@]}"; do
  if [[ "${profile}" != org:* && "${profile}" != repo:* ]]; then
    echo "~~~ :warning: Invalid profile: ${profile}. Must start with 'org:' or 'repo:'. Skipping configuration for this profile."
    continue
  fi
  git_config_add "credential.https://github.com.helper" "${plugin_root}/credential-helper/buildkite-connector-credential-helper ${chinmina_url} ${audience} ${profile}"
done

