#!/bin/bash
set -eou pipefail

url="${1:?url parameter required}"
audience="${2:?audience parameter required}"
profile="${3:?profile parameter required}"
action="${4:?action parameter required}"
: "${TMPDIR:?TMPDIR environment variable required}"

# ignore unsupported actions without error
if [[ "${action}" != "get" ]]; then
    exit 0
fi
# read credential helper input from stdin
args="$(< /dev/stdin)"

script_dir=$(dirname "${BASH_SOURCE[0]}")
# shellcheck source=../lib/cache.bash
source "${script_dir}/../lib/cache.bash"

# caches the OIDC token for 5 minutes, so that successive calls to the credential helper use the existing token
if ! oidc_auth_token="$(cache_read "${BUILDKITE_JOB_ID}")"; then
  # timings are output to stderr, which Git ignores.
  TIMEFORMAT='[oidc = %2Rs]'
  time {
    oidc_auth_token="$(buildkite-agent oidc request-token --claim pipeline_id --audience "${audience}")"
  }
  cache_write "${BUILDKITE_JOB_ID}" "${oidc_auth_token}"
fi

if [[ "${profile}" == repo:* ]]; then
  request_path="git-credentials"
else
  request_path="organization/git-credentials/${profile}"
fi

# Request a token for the given repository from the remote server, using the
# OIDC JWT from the agent. The output of this request is in the expected format,
# so is sent to stdout to be read by git.
TIMEFORMAT='[token vendor = %2Rs]'

time curl --silent --show-error --fail \
  --request POST "${url}/${request_path}" \
  --data "${args}" \
  --header "Authorization: Bearer ${oidc_auth_token}" \
  --header "Content-Type: text/plain" \
  --header "Accept: text/plain"

